
version: 0.0
os: centos
files:
  - source: / 
    destination: /home/centos/cdtest
hooks:
  ApplicationStop:
    - location: pm2 stop index -name "cdtest"
  AfterInstall:
    - location: pm2 start index -name "cdtest"