
version: 0.0
os: linux
files:
  - source: / 
    destination: /home/centos/cdtest

permissions:
- object: /home/centos
  owner: centos
  group: centos
  type:
    - directory
    - file

hooks:
  ApplicationStart:
    - location: /scripts/start_server
      timeout: 300
      runas: centos