
version: 0.0
os: linux
files:
  - source: / 
    destination: /home/centos/cdtest
permissions:
  - object: /home/centos/cdtest/scripts/
    pattern: "**"
    owner: centos
    group: centos
    mode: 777
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300