
version: 0.0
os: linux
files:
  - source: / 
    destination: /home/centos/cdtest
permissions:
  - object: /home/centos/cdtest/scripts
    pattern: "**"
    mode: 777

hooks:
  ApplicationStart:
    - location: /scripts/start_server
      timeout: 300