version: 0.1

permissions:
  - object: /home/centos
    owner: centos
    group: centos
    type:
      - directory
      - file
  - object: /home/centos/cdtest/scripts
    mode: +x
    type: 
      - file

phases:
  install:
    commands:
      npm install
    finally:
      - echo Install complete  
  build:
    commands:
      npm run build
    finally:
      - echo build complete
artifacts:
  files: 
  - '**/*'